/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.view;

import javax.swing.table.DefaultTableModel;
import uts.Databases.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class UserForm extends javax.swing.JFrame {

    Database db = new Database();
    
    public UserForm(String saldo, String nama) {
        initComponents();
        refreshData();
        setLocationRelativeTo(null);
        tabelBarang.getTableHeader().setReorderingAllowed(false);
        lblSaldo.setText(saldo);
        lblNama.setText("Selamat Datang "+nama);
        
    }
    
    private void refreshData(){
        DefaultTableModel model = (DefaultTableModel) tabelBarang.getModel();
        model.setRowCount(0);
        
        try {
            ResultSet values = db.executeSelectQuery("SELECT * FROM databarang");
            while (values.next()) {
                String idBarang = values.getString(1);
                String namaBarang = values.getString(2);
                String merkBarang = values.getString(3);
                String hargaBarang = values.getString(4);
                String jenisBarang = values.getString(5);
                
                String[] rowData = {idBarang,namaBarang,merkBarang,hargaBarang,jenisBarang};
                model.addRow(rowData);
                
            }   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtJenis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btnTopUp = new javax.swing.JButton();
        btnBeli = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Merk Barang", "Harga Barang", "Jenis Barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 304, 595, 233));

        txtID.setEditable(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 130, -1));

        txtNama.setEditable(false);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));

        txtMerk.setEditable(false);
        jPanel1.add(txtMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, -1));

        txtHarga.setEditable(false);
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, -1));

        txtJenis.setEditable(false);
        jPanel1.add(txtJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, -1));

        jLabel1.setText("ID Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setText("Nama Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setText("Merk Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Harga Barang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setText("Jenis Barang");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel6.setText("Saldo Anda :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 74, -1, -1));

        lblSaldo.setText("0");
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 74, 154, -1));

        btnTopUp.setText("TOP UP");
        btnTopUp.setPreferredSize(new java.awt.Dimension(100, 100));
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnTopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        btnBeli.setText("BELI");
        btnBeli.setPreferredSize(new java.awt.Dimension(100, 100));
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        jPanel1.add(btnBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));
        jPanel1.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        try {
            int saldoNow = Integer.parseInt(lblSaldo.getText());
            String topUpSaldo = JOptionPane.showInputDialog("MASUKKAN NOMINAL SALDO");
            if (!(topUpSaldo.length()>10)) {
                if (!topUpSaldo.matches("[a-zA-Z]+")) {
                    int saldoTopUp = Integer.parseInt(topUpSaldo);
                    int hasilSaldo = saldoNow + saldoTopUp;
                    String query = String.format("UPDATE akun SET saldo = '%d' WHERE username = '%s'", hasilSaldo,lblNama.getText().substring(15));
                    db.executeUpdateQuery(query);
                    JOptionPane.showMessageDialog(null, "BERHASIL TOPUP");
                    lblSaldo.setText(String.valueOf(hasilSaldo));
                }else JOptionPane.showMessageDialog(null, "DILARANG MEMASUKKAN HURUF ATAU SIMBOL");
            }else JOptionPane.showMessageDialog(null, "MASIMAL 9.999.999.999");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnTopUpActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        try {
            int selectedRow = tabelBarang.getSelectedRow();
            Object selectedID = tabelBarang.getValueAt(selectedRow, 0);
            String query = String.format("SELECT * FROM databarang WHERE ID_Barang = '%s'", selectedID);
            ResultSet values = db.executeSelectQuery(query);
            while (values.next()) {                
                txtID.setText(values.getString(1));
                txtNama.setText(values.getString(2));
                txtMerk.setText(values.getString(3));
                txtHarga.setText(values.getString(4));
                txtJenis.setText(values.getString(5));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        if (tabelBarang.getSelectedRow()== -1 || tabelBarang.getSelectedColumn() == -1) {
            JOptionPane.showMessageDialog(null, "HARAP PILIH BARANG DAHULU");
        }else{
            int saldo = Integer.parseInt(lblSaldo.getText());
            int harga = Integer.parseInt(txtHarga.getText());
            if (saldo >= harga) {
                try {
                    JOptionPane.showMessageDialog(null,"PEMBELIAN BERHASIL");
                    saldo -= harga;
                    lblSaldo.setText(String.valueOf(saldo));
                    String query = String.format("UPDATE akun SET saldo = '%d' WHERE username = '%s'", saldo,lblNama.getText().substring(15));
                    db.executeUpdateQuery(query);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "SALDO ANDA TIDAK CUKUP");
            }
        }
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "APAKAH ANDA YAKIN ?");
        if (answer == 1 || answer == 2 || answer == -1) {
            
        }else{
           this.dispose(); 
           new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm("99999999","GUEST").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
